filter:
  paths: ["src/*"]
  excluded_paths:
    - "**/__mocks__/"
    - "**/__tests__/"
build:
  tests:
    override:
      -
        command: 'npm t'
        coverage:
          file: './coverage/clover.xml'
          format: 'clover'
