export default {
  scopes: [
    'authors',
    'collections',
    'event-subscriptions',
    'events',
    'notifications',
    'orders',
    'products',
    'reviews',
    'questions',
    'statistics',
    'subscriptions',
    'support-levels',
    'transactions',
    'uploads',
    'user-auth-clients',
    'users',
    'templates',
    'membership-subscriptions',
    'tickets',
    'ticket-departments',
    'items',
    'loyalty-users',
    'payments',
    'payment-methods',
    'carts'
  ].join(' '),
};
