export const GET_USER_EMAIL_INFO_REQUEST = 'GET_USER_EMAIL_INFO_REQUEST';
export const GET_USER_EMAIL_INFO_SUCCESS = 'GET_USER_EMAIL_INFO_SUCCESS';
export const GET_USER_EMAIL_INFO_FAILURE = 'GET_USER_EMAIL_INFO_FAILURE';

export const POST_SIGNIN_AUTH_REQUEST = 'POST_SIGNIN_AUTH_REQUEST';
export const POST_SIGNIN_AUTH_SUCCESS = 'POST_SIGNIN_AUTH_SUCCESS';
export const POST_SIGNIN_AUTH_FAILURE = 'POST_SIGNIN_AUTH_FAILURE';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
